<?php
// languages.php - Multi-language support for FEDORA Admin Panel

$languages = [
    'en' => [
        'app_name' => 'FEDORA',
        'admin_panel' => 'Admin Panel',
        'admin_dashboard' => 'Admin Dashboard',
        'logout' => 'Logout',
        'login' => 'Login',
        'username' => 'Username',
        'password' => 'Password',
        'email' => 'Email',
        'phone' => 'Phone',
        'profile' => 'Profile',
        'settings' => 'Settings',
        'language_settings' => 'Language Settings',
        'manage_users' => 'Manage Users',
        'manage_sliders' => 'Manage Sliders',
        'manage_channels' => 'Manage Channels',
        'manage_movies' => 'Manage Movies',
        'manage_series' => 'Manage Series',
        'manage_categories' => 'Manage Categories',
        'manage_social' => 'Manage Social Links',
        'manage_sidebar' => 'Manage Sidebar',
        'add_slider' => 'Add Slider',
        'add_channel' => 'Add Channel',
        'add_movie' => 'Add Movie',
        'add_series' => 'Add Series',
        'add_category' => 'Add Category',
        'add_social' => 'Add Social Link',
        'add_user' => 'Add User',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'title' => 'Title',
        'name' => 'Name',
        'full_name' => 'Full Name',
        'url' => 'URL',
        'description' => 'Description',
        'image_url' => 'Image URL',
        'video_url' => 'Video URL',
        'm3u8_url' => 'M3U8 URL',
        'link_url' => 'Link URL',
        'category' => 'Category',
        'sort_order' => 'Sort Order',
        'status' => 'Status',
        'actions' => 'Actions',
        'created_at' => 'Created At',
        'updated_at' => 'Updated',
        'success' => 'Success',
        'error' => 'Error',
        'warning' => 'Warning',
        'confirm_delete' => 'Are you sure you want to delete this?',
        'deleted' => 'Deleted successfully',
        'updated' => 'Updated successfully',
        'created' => 'Created successfully',
        'select_language' => 'Select Language',
        'english' => 'English',
        'arabic' => 'العربية',
        'kurdish' => 'کوردی',
        'change_password' => 'Change Password',
        'current_password' => 'Current Password',
        'new_password' => 'New Password',
        'confirm_password' => 'Confirm Password',
        'profile_picture' => 'Profile Picture',
        'upload' => 'Upload',
        'users' => 'Users',
        'sliders' => 'Sliders',
        'channels' => 'Channels',
        'movies' => 'Movies',
        'series' => 'Series',
        'categories' => 'Categories',
        'social_links' => 'Social Links',
        'sidebar_items' => 'Sidebar Items',
        'role' => 'Role',
        'admin' => 'Admin',
        'user' => 'User',
        'active' => 'Active',
        'inactive' => 'Inactive',
        'all_sliders' => 'All Sliders',
        'all_channels' => 'All Channels',
        'all_movies' => 'All Movies',
        'all_series' => 'All Series',
        'all_categories' => 'All Categories',
        'total_users' => 'Total Users',
        'total_content' => 'Total Content',
        'recent_activities' => 'Recent Activities',
        'field_required' => 'This field is required',
        'invalid_email' => 'Invalid email',
        'password_mismatch' => 'Passwords do not match',
        'already_exists' => 'Already exists',
        'not_found' => 'Not found',
        'access_denied' => 'Access denied',
        'network_error' => 'Network error',
        'server_error' => 'Server error',
        'dashboard' => 'Dashboard',
        'welcome' => 'Welcome',
        'user_id' => 'User ID',
        'phone_number' => 'Phone Number',
        'member_since' => 'Member Since',
        'icon' => 'Icon',
        'route' => 'Route',
    ],
    'ar' => [
        'app_name' => 'فيدورا',
        'admin_panel' => 'لوحة التحكم',
        'admin_dashboard' => 'لوحة القيادة',
        'logout' => 'تسجيل الخروج',
        'login' => 'تسجيل الدخول',
        'username' => 'اسم المستخدم',
        'password' => 'كلمة المرور',
        'email' => 'البريد الإلكتروني',
        'phone' => 'رقم الهاتف',
        'profile' => 'الملف الشخصي',
        'settings' => 'الإعدادات',
        'language_settings' => 'إعدادات اللغة',
        'manage_users' => 'إدارة المستخدمين',
        'manage_sliders' => 'إدارة السلايدر',
        'manage_channels' => 'إدارة القنوات',
        'manage_movies' => 'إدارة الأفلام',
        'manage_series' => 'إدارة المسلسلات',
        'manage_categories' => 'إدارة الأقسام',
        'manage_social' => 'إدارة وسائل التواصل',
        'manage_sidebar' => 'إدارة القائمة الجانبية',
        'add_slider' => 'إضافة سلايدر',
        'add_channel' => 'إضافة قناة',
        'add_movie' => 'إضافة فيلم',
        'add_series' => 'إضافة مسلسل',
        'add_category' => 'إضافة قسم',
        'add_social' => 'إضافة وسيط تواصل',
        'add_user' => 'إضافة مستخدم',
        'edit' => 'تعديل',
        'delete' => 'حذف',
        'save' => 'حفظ',
        'cancel' => 'إلغاء',
        'title' => 'العنوان',
        'name' => 'الاسم',
        'full_name' => 'الاسم الكامل',
        'url' => 'الرابط',
        'description' => 'الوصف',
        'image_url' => 'رابط الصورة',
        'video_url' => 'رابط الفيديو',
        'm3u8_url' => 'رابط M3U8',
        'link_url' => 'رابط الربط',
        'category' => 'القسم',
        'sort_order' => 'ترتيب الفرز',
        'status' => 'الحالة',
        'actions' => 'الإجراءات',
        'created_at' => 'تاريخ الإنشاء',
        'updated_at' => 'التحديث',
        'success' => 'نجاح',
        'error' => 'خطأ',
        'warning' => 'تحذير',
        'confirm_delete' => 'هل تأكد من رغبتك في حذف هذا؟',
        'deleted' => 'تم الحذف بنجاح',
        'updated' => 'تم التحديث بنجاح',
        'created' => 'تم الإنشاء بنجاح',
        'select_language' => 'اختر اللغة',
        'english' => 'English',
        'arabic' => 'العربية',
        'kurdish' => 'کوردی',
        'change_password' => 'تغيير كلمة المرور',
        'current_password' => 'كلمة المرور الحالية',
        'new_password' => 'كلمة المرور الجديدة',
        'confirm_password' => 'تأكيد كلمة المرور',
        'profile_picture' => 'صورة الملف الشخصي',
        'upload' => 'رفع',
        'users' => 'المستخدمون',
        'sliders' => 'السلايدرات',
        'channels' => 'القنوات',
        'movies' => 'الأفلام',
        'series' => 'المسلسلات',
        'categories' => 'الأقسام',
        'social_links' => 'وسائل التواصل',
        'sidebar_items' => 'عناصر القائمة الجانبية',
        'role' => 'الدور',
        'admin' => 'إدمين',
        'user' => 'مستخدم',
        'active' => 'نشط',
        'inactive' => 'غير نشط',
        'all_sliders' => 'جميع السلايدرات',
        'all_channels' => 'جميع القنوات',
        'all_movies' => 'جميع الأفلام',
        'all_series' => 'جميع المسلسلات',
        'all_categories' => 'جميع الأقسام',
        'total_users' => 'إجمالي المستخدمين',
        'total_content' => 'إجمالي المحتوى',
        'recent_activities' => 'الأنشطة الأخيرة',
        'field_required' => 'هذا الحقل مطلوب',
        'invalid_email' => 'البريد الإلكتروني غير صحيح',
        'password_mismatch' => 'كلمات المرور لا تتطابق',
        'already_exists' => 'موجود بالفعل',
        'not_found' => 'غير موجود',
        'access_denied' => 'تم رفض الوصول',
        'network_error' => 'خطأ في الشبكة',
        'server_error' => 'خطأ في الخادم',
        'dashboard' => 'لوحة القيادة',
        'welcome' => 'أهلا وسهلا',
        'user_id' => 'معرف المستخدم',
        'phone_number' => 'رقم الهاتف',
        'member_since' => 'عضو منذ',
        'icon' => 'الرمز',
        'route' => 'المسار',
    ],
    'ku' => [
        'app_name' => 'فيدۆرا',
        'admin_panel' => 'پانێلی بەڕێوەبەری',
        'admin_dashboard' => 'داشبۆردی بەڕێوەبەری',
        'logout' => 'دەرچوون',
        'login' => 'چوونەژوورەوە',
        'username' => 'ناوی بەکاربێر',
        'password' => 'تێپەڕ',
        'email' => 'ئیمێیل',
        'phone' => 'مۆبایل',
        'profile' => 'پڕۆفایل',
        'settings' => 'سازانەکان',
        'language_settings' => 'سازانەی زمان',
        'manage_users' => 'بەڕێوەبەری بەکاربێران',
        'manage_sliders' => 'بەڕێوەبەری سلایدەر',
        'manage_channels' => 'بەڕێوەبەری چێنەلەکان',
        'manage_movies' => 'بەڕێوەبەری فلیمەکان',
        'manage_series' => 'بەڕێوەبەری سریزان',
        'manage_categories' => 'بەڕێوەبەری بەشەکان',
        'manage_social' => 'بەڕێوەبەری پەیوەندی کۆمەڵایەتی',
        'manage_sidebar' => 'بەڕێوەبەری بانی لاسۆکو',
        'add_slider' => 'زیادکردنی سلایدەر',
        'add_channel' => 'زیادکردنی چێنەل',
        'add_movie' => 'زیادکردنی فلیم',
        'add_series' => 'زیادکردنی سریز',
        'add_category' => 'زیادکردنی بەش',
        'add_social' => 'زیادکردنی پەیوەندی',
        'add_user' => 'زیادکردنی بەکاربێر',
        'edit' => 'دەستکاری',
        'delete' => 'سڕینەوە',
        'save' => 'پاشەکێشان',
        'cancel' => 'هەڵوەشاندن',
        'title' => 'سەردێڤ',
        'name' => 'ناو',
        'full_name' => 'ناوی تێدا',
        'url' => 'بەستەر',
        'description' => 'تێبینی',
        'image_url' => 'بەستەری وێنە',
        'video_url' => 'بەستەری ڤیدیۆ',
        'm3u8_url' => 'بەستەری M3U8',
        'link_url' => 'بەستەری بەستە',
        'category' => 'بەش',
        'sort_order' => 'ڕێزکردنی',
        'status' => 'دۆخ',
        'actions' => 'کردارەکان',
        'created_at' => 'ڕێکخستی',
        'updated_at' => 'نوێکردنەوە',
        'success' => 'سەرکەوتوویی',
        'error' => 'هەڵە',
        'warning' => 'ئاگاداری',
        'confirm_delete' => 'ئایا دڵنیایت لە سڕینەوەی ئەمە؟',
        'deleted' => 'بە سەرکەوتوویی سڕدرایەوە',
        'updated' => 'بە سەرکەوتوویی نوێکرایەوە',
        'created' => 'بە سەرکەوتوویی درووست کرا',
        'select_language' => 'زمانی هەڵبژێرە',
        'english' => 'English',
        'arabic' => 'العربية',
        'kurdish' => 'کوردی',
        'change_password' => 'گۆڕینی تێپەڕ',
        'current_password' => 'تێپەڕی ئێستا',
        'new_password' => 'تێپەڕی نوێ',
        'confirm_password' => 'دووبارە تێپەڕ',
        'profile_picture' => 'وێنەی پڕۆفایل',
        'upload' => 'بارکردن',
        'users' => 'بەکاربێران',
        'sliders' => 'سلایدەرەکان',
        'channels' => 'چێنەلەکان',
        'movies' => 'فلیمەکان',
        'series' => 'سریزان',
        'categories' => 'بەشەکان',
        'social_links' => 'پەیوەندی کۆمەڵایەتی',
        'sidebar_items' => 'بەشەکانی بانی لاسۆکو',
        'role' => 'ئاستی',
        'admin' => 'بەڕێوەبەر',
        'user' => 'بەکاربێر',
        'active' => 'چالاک',
        'inactive' => 'نەچالاک',
        'all_sliders' => 'هەموو سلایدەرەکان',
        'all_channels' => 'هەموو چێنەلەکان',
        'all_movies' => 'هەموو فلیمەکان',
        'all_series' => 'هەموو سریزان',
        'all_categories' => 'هەموو بەشەکان',
        'total_users' => 'کۆی بەکاربێران',
        'total_content' => 'کۆی ناوەڕۆکی',
        'recent_activities' => 'چالاکی داهاتوو',
        'field_required' => 'ئەم خانەیە پێویست بێت',
        'invalid_email' => 'ئیمێیلی دروست نیە',
        'password_mismatch' => 'تێپەڕەکان یەکسان نین',
        'already_exists' => 'بەهێز هەیە',
        'not_found' => 'نەدۆزرایەوە',
        'access_denied' => 'دەستگێڕی پێیەدا رێج',
        'network_error' => 'هەڵەی ڕایۆ',
        'server_error' => 'هەڵەی سێڕڤەر',
        'dashboard' => 'داشبۆرد',
        'welcome' => 'بەخێرتۆ',
        'user_id' => 'ناسنامەی بەکاربێر',
        'phone_number' => 'ژمارەی مۆبایل',
        'member_since' => 'ئیندیکە لە',
        'icon' => 'ئایکۆن',
        'route' => 'بەستە',
    ]
];

// Get language from URL parameter, cookie, or session
$lang = $_GET['lang'] ?? $_COOKIE['app_language'] ?? $_SESSION['app_language'] ?? 'en';
$lang = in_array($lang, ['en', 'ar', 'ku']) ? $lang : 'en';

// Set cookie
setcookie('app_language', $lang, time() + (86400 * 30), '/');

// Helper function to translate
function t($key, $replacements = []) {
    global $lang, $languages;
    
    $text = $languages[$lang][$key] ?? $languages['en'][$key] ?? $key;
    
    foreach ($replacements as $search => $replace) {
        $text = str_replace(':' . $search, $replace, $text);
    }
    
    return $text;
}

function is_rtl_language($language = null) {
    global $lang;
    $language = $language ?? $lang;
    return in_array($language, ['ar', 'ku']);
}

function get_text_direction($language = null) {
    return is_rtl_language($language) ? 'rtl' : 'ltr';
}

function get_html_lang() {
    global $lang;
    return $lang;
}
?>
